name: Trigger OpenSIPS Control Panel Docker Image build and publish

on:
  push:
  repository_dispatch:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set docker-tag variable
      run:  BRANCH="${GITHUB_REF#refs/heads/}"; echo -e "BRANCH=$BRANCH\nDOCKER_TAG=${BRANCH//master/latest}" >> $GITHUB_ENV
    
    - name: Repository Dispatch
      uses: actions/github-script@v8
      with:
        github-token: ${{ secrets.DOCKER_OPENSIPS_CLI_PAT }}
        script: |
          await github.rest.repos.createDispatchEvent({
            owner: 'OpenSIPS',
            repo: 'docker-opensips-cp',
            event_type: 'OpenSIPS CP trigger',
            client_payload: {
              docker_tag: process.env.DOCKER_TAG,
              branch: process.env.BRANCH
            }
          });
